name = "JuliaExampleComponents"
uuid = "4f289198-a466-4861-a6bd-1e7b09ed8707"
authors = ["Daniel Ingraham <d.j.ingraham@gmail.com>"]
version = "0.1.0"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ImplicitAD = "e7cbb90b-9b31-4eb2-a8c8-45099c074ee1"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OpenMDAOCore = "24d19c10-6eee-420f-95df-4537264b2753"
SparseMatrixColorings = "0a514795-09f3-496d-8182-132a7b665d35"

[compat]
ADTypes = "1.14.0"
ComponentArrays = "0.15.27"
ForwardDiff = "1.0.1"
ImplicitAD = "1.1.0"
LineSearches = "7.5.1"
NLsolve = "4.5.1"
OpenMDAOCore = "0.3.2"
SparseMatrixColorings = "0.4.19"
